chezmoiscripts: refactor package install script
- print packages in an inline loop instead of adding them to arrays

diff --git a/.chezmoiscripts/run_onchange_before_10-install-package.sh.tmpl b/.chezmoiscripts/run_onchange_before_10-install-package.sh.tmpl
--- a/.chezmoiscripts/run_onchange_before_10-install-package.sh.tmpl
+++ b/.chezmoiscripts/run_onchange_before_10-install-package.sh.tmpl
@@ -4,22 +4,14 @@
 
 {{- if (eq "arch" .chezmoi.osRelease.id (get .chezmoi.osRelease "idLike")) -}}
 
-{{ range .packages.arch.pacman }}
-packages+=({{- . | quote -}})
-{{- end }}
-
-{{ range .packages.arch.aur }}
-aur_packages+=({{- . | quote -}})
-{{- end }}
-
 if _install_confirm "${BOLD}Install base packages? [Y/n]${NC} "; then
   echo -e "\n${BLUE_BOLD}===>  ${NC}${BOLD}Installing base packages...${NC}\n"
-  {{ .aurHelper }} -S --needed "${packages[@]}" || echo -e "\n${YELLOW_BOLD}WARNING: ${NC}Package installation failed or cancelled by user.\n"
+  {{ .aurHelper }} -S --needed {{ range .packages.arch.pacman }}{{ . | quote }} {{ end -}} || echo -e "\n${YELLOW_BOLD}WARNING: ${NC}Package installation failed or cancelled by user.\n"
 fi
 
 if _install_confirm "${BOLD}Install AUR packages? [Y/n]${NC} "; then
   echo -e "\n${BLUE_BOLD}===>  ${NC}${BOLD}Installing AUR packages...${NC}\n"
-  {{ .aurHelper }} -S --needed "${aur_packages[@]}" || echo -e "\n${YELLOW_BOLD}WARNING: ${NC}Package installation failed or cancelled by user.\n"
+  {{ .aurHelper }} -S --needed {{ range .packages.arch.aur }}{{ . | quote }} {{ end -}} || echo -e "\n${YELLOW_BOLD}WARNING: ${NC}Package installation failed or cancelled by user.\n"
 fi
 
 {{- else -}}
