.chezmoiscripts: warning on cancelled/failed installing pacman/AUR packages

diff --git a/.chezmoiscripts/run_onchange_before_10-install-pacman.sh.tmpl b/.chezmoiscripts/run_onchange_before_10-install-pacman.sh.tmpl
--- a/.chezmoiscripts/run_onchange_before_10-install-pacman.sh.tmpl
+++ b/.chezmoiscripts/run_onchange_before_10-install-pacman.sh.tmpl
@@ -1,5 +1,8 @@
 #!/usr/bin/env bash
 
+ORANGE='\033[0;33m'
+NC='\033[0m' # No Color
+
 {{ range .packages.pacman }}
 packages+=({{- . | quote -}})
 {{- end }}
@@ -18,5 +21,5 @@ _install_confirm() {
 
 if _install_confirm "Install base packages? [Y/n] " -eq 0; then
   echo -e "\n===>  Installing base packages...\n"
-  {{ .chezmoi.config.data.aurHelper }} -S --needed "${packages[@]}"
+  {{ .chezmoi.config.data.aurHelper }} -S --needed "${packages[@]}" || echo -e "\n${ORANGE}WARNING${NC}: Package installation failed or cancelled by user.\n"
 fi
